### ISSUE TITLE
bokeh.charts library is outdated

### ISSUE THREAD

**Issue by dummyscientist** [woodenleaves/PubMed#1]
The library deprecated long time ago and removed. You can find information and alternative at: https://stackoverflow.com/questions/48170086/what-to-use-instead-of-bokeh-charts

**Comment by wdlv** [comment]
Thanks for telling me! The script was written many years ago and I haven't used bokeh since then. It seems the script is using bokeh just for some simple bar chars. I believe there are many alternative visualization packages available and you could just use your preferred one to replace it.
